language: go
sudo: false

go:
  - "1.13.x"
  - "1.x"
  - tip

os:
- linux
- osx
- windows

allow_failures:	
  - go: tip
  - os: windows

before_script:
  - go vet ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)