language: go
sudo: false

go:
  - "1.13.x"
  - "1.x"
  # - tip

os:
- linux
- osx
- windows

# matrix:
#   allow_failures:	
#     - go: tip
#       os: windows

before_install:
  - go get -t -v ./...

before_script:
  - go vet ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)